# Generated by Django 5.2.1 on 2025-05-27 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'عميل', 'verbose_name_plural': 'العملاء'},
        ),
        migrations.AlterModelOptions(
            name='clientphonenumber',
            options={'verbose_name': 'رقم هاتف العميل', 'verbose_name_plural': 'أرقام هواتف العميل'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'فاتورة', 'verbose_name_plural': 'الفواتير'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'دفعة', 'verbose_name_plural': 'الدفعات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'مورد', 'verbose_name_plural': 'الموردين'},
        ),
        migrations.AlterModelOptions(
            name='supplierphonenumber',
            options={'verbose_name': 'رقم هاتف المورد', 'verbose_name_plural': 'أرقام هواتف المورد'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='invoice_count',
        ),
        migrations.RemoveField(
            model_name='client',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='clientphonenumber',
            name='number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='cooperation_end_date',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='cooperation_start_date',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='total_orders',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='supplierphonenumber',
            name='description',
        ),
        migrations.RemoveField(
            model_name='supplierphonenumber',
            name='number',
        ),
        migrations.AddField(
            model_name='clientphonenumber',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid', 'مدفوعة'), ('unpaid', 'غير مدفوعة'), ('pending', 'معلقة')], default='unpaid', max_length=20, verbose_name='حالة الفاتورة'),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر الافتراضي'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='كود المنتج'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المنتج'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='كمية المخزون'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء التعاون'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_method',
            field=models.CharField(choices=[('30_days', '30 يوم'), ('60_days', '60 يوم')], default='30_days', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بدء التعاون'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='type',
            field=models.CharField(choices=[('individual', 'فرد'), ('company', 'شركة')], default='company', max_length=20, verbose_name='النوع'),
        ),
        migrations.AddField(
            model_name='supplierphonenumber',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='client',
            name='business_type',
            field=models.CharField(choices=[('individual', 'فرد'), ('company', 'شركة')], max_length=20, verbose_name='نوع العمل'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='client',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهوية الوطنية'),
        ),
        migrations.AlterField(
            model_name='client',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي'),
        ),
        migrations.AlterField(
            model_name='clientphonenumber',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='accounting.client', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='clientphonenumber',
            name='description',
            field=models.CharField(max_length=100, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.client', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(verbose_name='تاريخ الفاتورة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('purchase', 'شراء'), ('sales', 'بيع')], max_length=20, verbose_name='نوع الفاتورة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.supplier', verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounting.invoice', verbose_name='الفاتورة'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(verbose_name='تاريخ الدفع'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(max_length=50, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qr_code',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='رمز QR'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.PositiveIntegerField(verbose_name='مستوى إعادة الطلب'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.supplier', verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_type',
            field=models.CharField(choices=[('amount', 'مبلغ ثابت'), ('percent', 'نسبة مئوية')], max_length=20, verbose_name='نوع الضريبة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الضريبة'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='كود المورد'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tax_number',
            field=models.CharField(max_length=50, verbose_name='الرقم الضريبي'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='الشروط والأحكام'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='الموقع الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='supplierphonenumber',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='الرئيسي'),
        ),
        migrations.AlterField(
            model_name='supplierphonenumber',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='accounting.supplier', verbose_name='المورد'),
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الخصم')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.invoice', verbose_name='الفاتورة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'سطر فاتورة',
                'verbose_name_plural': 'سطور الفاتورة',
            },
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
