# Generated by Django 5.2.1 on 2025-05-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_dashboardstats_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='total_orders',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
