# Generated by Django 5.2.1 on 2025-05-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_supplier_total_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='client_name_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['national_id'], name='client_national_id_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tax_number'], name='client_tax_number_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoice_number_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='invoice_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payment_date_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='product_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='product_code_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['quantity_in_stock'], name='product_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='supplier_name_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['supplier_code'], name='supplier_code_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['tax_number'], name='supplier_tax_number_idx'),
        ),
    ]
